import type { Config } from "tailwindcss";

const config: Config = {
	content: [
		"./src/**/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/components/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/app/**/*.{js,ts,jsx,tsx,mdx}",
	],
	theme: {
		screens: {
			xxxl: { max: "3019px" },
			xxl: { max: "2560px" },
			xl: { max: "1920px" },
			"desktop-l": { max: "1880px" },
			"desktop-m": { max: "1680px" },
			"laptop-x": { max: "1440px" },
			"laptop-m": { max: "1280px" },
			lg: { max: "1170px" },
			md: { max: "991px" },
			sm: { max: "767px" },
			xs: { max: "414px" },
			xxs: { max: "375px" },
			"2xl": "1921px",
			DEFAULT: "1200px",
		},
		container: {
			center: true,
			padding: {
				DEFAULT: "26px",
				xxl: "26px",
				xl: "26px",
				lg: "24px",
				md: "20px",
				sm: "16px",
				xs: "15px",
			},
		},

		fontFamily: {
			primary: ["Lustria", "serif"],
			secondary: ["Poppins", "sans-serif"],
		},
		fontSize: {
			"heading-h1": "48px",
			"heading-h2": "40px",
			"heading-h3": "32px",
			"heading-h4": "24px",
			text: "16px",
			"body-large": "20px",
			"body-medium": "18px",
			"body-regular": "16px",
			"body-small": "14px",
			"body-caption": "12px",
			"body-form": "11px",
			"body-eyebrow-large": "14px",
			"body-eyebrow-medium": "12px",
			"body-eyebrow-small": "10px",
			"body-bold-large": "22px",
			"body-bold-medium": "18px",
			"body-bold-regular": "16px",
			"body-bold-small": "14px",
			"body-bold-caption": "12px",
			"body-bold-form": "11px",
		},
		extend: {
			colors: {
				"mono-100": "#0B0112",
				"mono-90": "#474648",
				"mono-80": "#6B686E",
				"mono-70": "#8A888C",
				"mono-50": "#C9C8CA",
				"mono-40": "#C9C8CA",
				"mono-0": "#FFFFFF",
				"mono-60": "#AAA7AB",
				error: "#D10C3B",
				success: "#1FC430",
				"secondary-color-100": "#1B264F",
				"primary-color-100": "#611192",
				"primary-color-50": "#3B055C",
				"primary-color-70": "#F2E8F8",
			},
			backgroundImage: {
				"inner-cta":
					"linear-gradient(96.34deg,#926AFF 0%,#FF77B0 50%,#FFB367 100%)",
			},
			gridTemplateColumns: {
				"16": "repeat(16, minmax(0, 1fr))",
			},
			gridColumn: {
				"span-13": "span 13 / span 13",
				"span-14": "span 14 / span 14",
				"span-15": "span 15 / span 15",
				"span-16": "span 16 / span 16",
			},
		},
	},
	plugins: [require("daisyui")],
};
export default config;
