export const categoriesData = {
  categories: [
    {
      id: 'women',
      name: 'Women',
      subCategories: [
        { id: 'skirts', name: 'Skirts' },
        { id: 'trousers', name: 'Trousers' },
        { id: 'tops', name: 'Tops' },
        { id: 'knitwear', name: 'Knitwear' },
        { id: 'dresses', name: 'Dresses' },
        { id: 'jeans', name: 'Jeans' },
        { id: 'jackets', name: 'Jackets' },
        { id: 'jumpsuits', name: 'Jumpsuits' },
        { id: 'coats', name: 'Coats' },
        { id: 'leather-jackets', name: 'Leather Jackets' },
        { id: 'trench-coats', name: 'Trench Coats' },
        { id: 'swimwear', name: 'Swimwear' },
        { id: 'shorts', name: 'Shorts' },
      ],
    },
    {
      id: 'men',
      name: 'Men',
      subCategories: [
        { id: 'shirts', name: 'Shirts' },
        { id: 'trousers', name: 'Trousers' },
        { id: 'jackets', name: 'Jackets' },
        { id: 'jeans', name: 'Jeans' },
        { id: 'coats', name: 'Coats' },
      ],
    },
    {
      id: 'children',
      name: 'Children',
      subCategories: [
        { id: 'clothing', name: 'Clothing' },
        { id: 'shoes', name: 'Shoes' },
        { id: 'accessories', name: 'Accessories' },
      ],
    },
    {
      id: 'clothing',
      name: 'Clothing',
      subCategories: [
        { id: 'skirts', name: 'Skirts' },
        { id: 'trousers', name: 'Trousers' },
        { id: 'tops', name: 'Tops' },
        { id: 'knitwear', name: 'Knitwear' },
        { id: 'dresses', name: 'Dresses' },
        { id: 'jeans', name: 'Jeans' },
        { id: 'jackets', name: 'Jackets' },
        { id: 'jumpsuits', name: 'Jumpsuits' },
        { id: 'coats', name: 'Coats' },
        { id: 'leather-jackets', name: 'Leather Jackets' },
        { id: 'trench-coats', name: 'Trench Coats' },
        { id: 'swimwear', name: 'Swimwear' },
        { id: 'shorts', name: 'Shorts' },
      ],
    },
    {
      id: 'shoes',
      name: 'Shoes',
      subCategories: [
        { id: 'boots', name: 'Boots' },
        { id: 'trainers', name: 'Trainers' },
        { id: 'flats', name: 'Flats' },
        { id: 'sandals', name: 'Sandals' },
        { id: 'clogs', name: 'Clogs' },
        { id: 'heels', name: 'Heels' },
      ],
    },
    {
      id: 'bags',
      name: 'Bags',
      subCategories: [
        { id: 'handbags', name: 'Handbags' },
        { id: 'clutch-bags', name: 'Clutch Bags' },
        { id: 'backpacks', name: 'Backpacks' },
        { id: 'travel-bags', name: 'Travel Bags' },
        { id: 'suitcases', name: 'Suitcases' },
        { id: 'luggage-bags', name: 'Luggage Bags' },
      ],
    },
    {
      id: 'accessories',
      name: 'Accessories',
      subCategories: [
        { id: 'sunglasses', name: 'Sunglasses' },
        { id: 'wallets', name: 'Wallets' },
        { id: 'belts', name: 'Belts' },
        { id: 'hats', name: 'Hats' },
        { id: 'scarves', name: 'Scarves' },
        { id: 'purses', name: 'Purses' },
        { id: 'hair-accessories', name: 'Hair Accessories' },
        { id: 'pins-brooches', name: 'Pins & Brooches' },
      ],
    },
    {
      id: 'jewellery',
      name: 'Jewellery',
      subCategories: [
        { id: 'earrings', name: 'Earrings' },
        { id: 'necklaces', name: 'Necklaces' },
        { id: 'watches', name: 'Watches' },
        { id: 'rings', name: 'Rings' },
        { id: 'bracelets', name: 'Bracelets' },
        { id: 'jewellery-sets', name: 'Jewellery Sets' },
        { id: 'bag-charms', name: 'Bag Charms' },
      ],
    },
    {
      id: 'homeware',
      name: 'Homeware',
      subCategories: [
        { id: 'furniture', name: 'Furniture' },
        { id: 'decor', name: 'Decor' },
        { id: 'kitchenware', name: 'Kitchenware' },
      ],
    },
    {
      id: 'books',
      name: 'Books',
      subCategories: [
        { id: 'fiction', name: 'Fiction' },
        { id: 'non-fiction', name: 'Non-Fiction' },
        { id: 'children-books', name: "Children's Books" },
      ],
    },
    {
      id: 'electronics',
      name: 'Electronics',
      subCategories: [
        { id: 'phones', name: 'Phones' },
        { id: 'laptops', name: 'Laptops' },
        { id: 'tablets', name: 'Tablets' },
      ],
    },
  ],
};
