import { Product } from '@/types/productTypes';

export const productData: Product[] = [
  {
    id: 1,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers',
    condition: 'New',
    status: 'LIVE',
    stock: 10, // Number of items available
    averageDeliveryTime: 5, // Average delivery time in days
  },
  {
    id: 2,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers',
    condition: 'Very Good Condition',
    status: 'Draft', // Draft status indicates the product is not publicly available yet
    stock: 5, // Current stock of the product
    averageDeliveryTime: 7, // Average delivery time in days
  },
  {
    id: 3,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs',
    condition: 'Good Condition',
    status: 'LIVE',
    stock: 15,
    averageDeliveryTime: 4, // Average delivery time in days
  },
  {
    id: 4,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors',
    condition: 'Fair Condition',
    status: 'Removed', // This product has been removed, possibly due to zero stock
    stock: 0, // Out of stock
    averageDeliveryTime: 10, // Average delivery time in days
  },
  // Add more products here with all required fields filled in
  {
    id: 5,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers',
    condition: 'New',
    status: 'LIVE',
    stock: 7,
    averageDeliveryTime: 5, // Average delivery time in days
  },
  {
    id: 6,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers',
    condition: 'Very Good Condition',
    status: 'Draft',
    stock: 8,
    averageDeliveryTime: 7, // Average delivery time in days
  },
  {
    id: 7,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs',
    condition: 'Good Condition',
    status: 'LIVE',
    stock: 20,
    averageDeliveryTime: 4, // Average delivery time in days
  },
  {
    id: 8,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors',
    condition: 'Fair Condition',
    status: 'Removed',
    stock: 0,
    averageDeliveryTime: 10, // Average delivery time in days
  },
  {
    id: 9,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers',
    condition: 'New',
    status: 'LIVE',
    stock: 4,
    averageDeliveryTime: 5, // Average delivery time in days
  },
  {
    id: 10,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers',
    condition: 'Very Good Condition',
    status: 'Draft',
    stock: 10,
    averageDeliveryTime: 7, // Average delivery time in days
  },
  {
    id: 11,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs',
    condition: 'Good Condition',
    status: 'LIVE',
    stock: 15,
    averageDeliveryTime: 4, // Average delivery time in days
  },
  {
    id: 12,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs',
    condition: 'Good Condition',
    status: 'Removed',
    stock: 0,
    averageDeliveryTime: 10, // Average delivery time in days
  },
  {
    id: 13,
    charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors',
    condition: 'Fair Condition',
    status: 'LIVE',
    stock: 5,
    averageDeliveryTime: 6, // Average delivery time in days
  },
];
