import { Product } from '@/types/productTypes';

export const productData: Product[] = [
  {
    id: 1,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 2,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 3,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 4,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 5,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 6,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 7,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 8,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 9,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 10,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 11,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 12,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 13,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 14,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 15,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 16,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 17,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 18,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 19,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 20,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 21,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 22,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 23,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 24,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 25,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 26,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 27,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 28,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 29,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 30,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 31,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 32,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 33,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 34,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 35,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 36,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
  {
    id: 37,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img4.png',
    charityImageAlt: 'Decor Logo',
    productImageSrc: '/images/products/product4.png',
    productImageAlt: 'Balineum Flora Wall Mirror',
    brand: 'Balineum',
    name: 'Flora Wall Mirror',
    size: '100x100',
    price: '15.00',
    location: 'London',
    category: 'Home Decor',
    subcategory: 'Mirrors', // Added subcategory
    condition: 'Fair Condition',
  },
  {
    id: 37,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img.png',
    charityImageAlt: 'The Salvation Army Logo',
    productImageSrc: '/images/products/product1.png',
    productImageAlt: 'Hollister Crew Neck Jumper',
    brand: 'Hollister',
    name: 'Crew Neck Jumper',
    size: '12 UK',
    price: '11.50',
    location: 'London',
    category: 'Clothing',
    subcategory: 'Jumpers', // Added subcategory
    condition: 'New',
  },
  {
    id: 38,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img2.png',
    charityImageAlt: 'RSPCA Logo',
    productImageSrc: '/images/products/product2.png',
    productImageAlt: 'Jordan Dunks',
    brand: 'Jordan',
    name: 'Jordan Dunks',
    size: '10 UK',
    price: '40.00',
    location: 'London',
    category: 'Footwear',
    subcategory: 'Sneakers', // Added subcategory
    condition: 'Very Good Condition',
  },
  {
    id: 40,
     charity: {
      charityName: 'string',
      profileImage: 'string',
    },
    seller: {
      firstName: 'string',
      lastName: 'string',
      profileImages: 'string',
      address: {
        city: 'string',
        country: 'string',
      },
    },
     images: [
      { url: 'string', altText: 'string' },
    ],
    charityImageSrc: '/images/icons/charity-img3.png',
    charityImageAlt: 'WaterAid Logo',
    productImageSrc: '/images/products/product3.png',
    productImageAlt: 'Addison Ross Fine Bone China Mug',
    brand: 'Addison Ross',
    name: 'Fine Bone China Mug',
    size: 'N/A',
    price: '3.00',
    location: 'London',
    category: 'Kitchenware',
    subcategory: 'Cups & Mugs', // Added subcategory
    condition: 'Good Condition',
  },
];
