export const productData = [
    
	{
		
        id: 1,
        charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 2,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 3,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 4,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
	{
		
        id: 5,
        charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 6,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 7,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 8,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 9,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 10,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
    {
		
        id: 11,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 12,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 13,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 14,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 15,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 16,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 17,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 18,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 19,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 20,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 21,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 22,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 23,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 24,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 25,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 26,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 27,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 28,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 29,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},	{
		
        id: 30,
        charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id:31,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 32,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 33,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 34,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 35,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 36,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	},
	{
		
        id: 37,
        charityImageSrc: "/images/icons/charity-img4.png",
		charityImageAlt: "Decor Logo",
		productImageSrc: "/images/products/product4.png",
		productImageAlt: "Balineum Flora Wall Mirror",
		productBrand: "Balineum",
		productTitle: "Flora Wall Mirror",
		productSize: "100x100",
		productPrice: "15.00",
		location: "London",
		category: "Home Decor",
		subcategory: "Mirrors", // Added subcategory
		productCondition: "Fair Condition",
	},
    	{
		
        id: 37,
            charityImageSrc: "/images/icons/charity-img.png",
		charityImageAlt: "The Salvation Army Logo",
		productImageSrc: "/images/products/product1.png",
		productImageAlt: "Hollister Crew Neck Jumper",
		productBrand: "Hollister",
		productTitle: "Crew Neck Jumper",
		productSize: "12 UK",
		productPrice: "11.50",
		location: "London",
		category: "Clothing",
		subcategory: "Jumpers", // Added subcategory
		productCondition: "New",
	},
	{
		
        id: 38,
        charityImageSrc: "/images/icons/charity-img2.png",
		charityImageAlt: "RSPCA Logo",
		productImageSrc: "/images/products/product2.png",
		productImageAlt: "Jordan Dunks",
		productBrand: "Jordan",
		productTitle: "Jordan Dunks",
		productSize: "10 UK",
		productPrice: "40.00",
		location: "London",
		category: "Footwear",
		subcategory: "Sneakers", // Added subcategory
		productCondition: "Very Good Condition",
	},
	{
		
        id: 40,
        charityImageSrc: "/images/icons/charity-img3.png",
		charityImageAlt: "WaterAid Logo",
		productImageSrc: "/images/products/product3.png",
		productImageAlt: "Addison Ross Fine Bone China Mug",
		productBrand: "Addison Ross",
		productTitle: "Fine Bone China Mug",
		productSize: "N/A",
		productPrice: "3.00",
		location: "London",
		category: "Kitchenware",
		subcategory: "Cups & Mugs", // Added subcategory
		productCondition: "Good Condition",
	}
    
];
