import type { Metadata } from 'next';
import './globals.css';
import '@/styles/styles.css';
import ToastNotification from '@/components/elements/notifications/ToastService';
export const metadata: Metadata = {
  title: 'Angelpage Charity Based E-commerce webapp',
  description: 'Generated by create next app',
  icons: { icon: '/images/favicon.png', apple: '/images/favicon.png' },
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <html lang="en">
        <body className="angelpage-body-wrapper-area">
          <main className="angelpage-main-wrapper">
           <ToastNotification />
            {children}
            </main>
        </body>
      </html>
  );
}
