'use client';

import React from 'react';
import './globals.css';
import '@/styles/styles.css';
import { Provider } from 'react-redux';
import store from '@/store/store';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}

// import './globals.css';
// import '@/styles/styles.css';
// import type { Metadata } from 'next';
// import ClientProviders from '@/utils/Provider';

// // Metadata export for server-side configuration
// export const metadata: Metadata = {
//   title: 'Angelpage Charity Based E-commerce webapp',
//   description: 'Generated by create next app',
//   icons: { icon: '/images/favicon.png', apple: '/images/favicon.png' },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="angelpage-body-wrapper-area">
//         <main className="angelpage-main-wrapper">
//           <ClientProviders>{children}</ClientProviders>
//         </main>
//       </body>
//     </html>
//   );
// }
